### ISSUE TITLE
dosnt do what it says

### ISSUE THREAD

**Issue by kres0345** [ash47/OmegleMiddleMan#17]
easy to use gatta say... after my experince it dosnt do mitm it just connects you to a stranger not two strangers

**Comment by ash47** [comment]
Are you joking? You are meant to connect to two strangers at once, by
creating two windows, then you use through buttons at the button to
automatically route the traffic between two or more windows

On 22 Feb 2017 3:58 AM, "kres0345" <notifications@github.com> wrote:

easy to use gatta say... after my experince it dosnt do mitm it just
connects you to a stranger not two strangers

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ash47/OmegleMiddleMan/issues/17>, or mute the thread

**Comment by kres0345** [comment]
but then it is not mitm

**Comment by ash47** [comment]
It's absolutely man in the middle -- you can watch them chat, you can turn
off auto broadcast of you want to manually check every message

You can also inject other messages into their chats

On 23 Feb 2017 8:14 PM, "kres0345" <notifications@github.com> wrote:

but then it is not mitm

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ash47/OmegleMiddleMan/issues/17#issuecomment-281937326>,
or mute the thread
